### ISSUE TITLE
Team 09 SRS Review: UC4

### ISSUE THREAD

**Issue by DangJustin** [d-akselrod/SweatSmart#50]
I found that the requirement UC4 under section 5.3 is a bit confusing. The requirement and the formal specification of the requirement seem to be different. The requirement says "The system should list all exercises", but the formal specification just seems to state that the list of exercises is not null. I think some formal specification like "For all exercises: exercise is an element of the list of exercises" would better specify the requirement.

@CSchank

**Comment by sophiefillion** [comment]
change applied
