### ISSUE TITLE
Team 09 SRS Review - Functional Requirements

### ISSUE THREAD

**Issue by FardeenAfsar** [d-akselrod/SweatSmart#51]
The issue highlighted in the SRS is for a specific functional requirement, AF1, which states that the app should allow users to begin a planned workout and track it live. The concern here is that these two functionalities, starting a workout and live tracking, are combined into a single requirement. By separating these functionalities into distinct requirements, it allows for clearer development, testing, and potentially easier modification or expansion of these features in the future.

**Comment by DangJustin** [comment]
@CSchank

**Comment by sophiefillion** [comment]
fixed requirement
