### ISSUE TITLE
Team 09 SRS Review - Health and Safety Exercise Restrictions

### ISSUE THREAD

**Issue by FardeenAfsar** [d-akselrod/SweatSmart#52]
In the SRS, it mentions that the system will have the capability to restrict certain exercises based on the user's specific health conditions. However, it does not provide specific details about which health conditions will trigger these restrictions or which exercises will be restricted for users with certain conditions. For example, if a user has a heart condition, the system should restrict high-intensity cardio exercises.

**Comment by DangJustin** [comment]
@CSchank
