### ISSUE TITLE
Team 09 - SRS Review - Non-functional Requirements 

### ISSUE THREAD

**Issue by HamidHarris** [d-akselrod/SweatSmart#53]
Under section 6.1.1, APR4 should have a fit criterion e.g. 500 ms response time, to be able to measure the quality.
Under section 6.3, it states "The system shall achieve a minimum of 99.9". PR2 lacks context, 99.9 of what? uptime?

**Comment by HamidHarris** [comment]
@CSchank

**Comment by sophiefillion** [comment]
1. change applied
2. latex typo fixed
