### ISSUE TITLE
Team 09 - SRS Review - Functional Requirement WH1

### ISSUE THREAD

**Issue by Lazarus-XD** [d-akselrod/SweatSmart#54]
In the requirement WH1, it mentions about displaying the user's workout history. However, in the formal specification of the requirement it only mentions when the user is not null, it will display the history. It fails to mention what will happen when the user only created an account or user hasn't completed a workout and tries to view the workout history. So, there should also be another clause mentioning user has completed one workout before and user is not new then history will not be null.

@CSchank

**Comment by sophiefillion** [comment]
change applied
