### ISSUE TITLE
Team 09 Hazard Analysis Review - Critical Assumptions

### ISSUE THREAD

**Issue by DangJustin** [d-akselrod/SweatSmart#97]
I think that one critical assumption that you probably should add to the Hazard Analysis is the phone being functional and being able to support the SweatSmart application. This way you would not need to consider the hazard of a user device crashing because of the device not supporting SweatSmart in the FMEA table.  This hazard otherwise would be very difficult to mitigate within the scope of the SweatSmart application.

@Cschank

**Comment by sophiefillion** [comment]
updated hazard analysis with this change
